import { 
  Link2, 
  FileText, 
  Play, 
  Radio, 
  Mail, 
  Users, 
  CreditCard, 
  ArrowUpCircle, 
  ArrowDownCircle,
  CheckCircle, 
  StickyNote,
  Smartphone,
  Zap,
  Percent,
  ShoppingCart,
  Repeat,
  Lock,
  PhoneCall,
  Clock,
  Package,
  Send
} from 'lucide-react';

export const ICON_MAP: Record<string, any> = {
  bio: Link2,
  landing: FileText,
  vsl: Play,
  webinar: Radio,
  email: Mail,
  grupo: Users,
  checkout: CreditCard,
  orderbump: Zap,
  upsell: ArrowUpCircle,
  downsell: ArrowDownCircle,
  discount: Percent,
  abandonment: ShoppingCart,
  subscription: Repeat,
  membership: Lock,
  trial: Clock,
  bundle: Package,
  sales_call: PhoneCall,
  thankyou: CheckCircle,
  note: StickyNote,
  product_main: Package,
  product_bump: Zap,
  product_upsell: ArrowUpCircle,
  product_downsell: ArrowDownCircle,
  facebook: Smartphone,
  instagram: Smartphone,
  tiktok: Smartphone,
  youtube: Play,
  linkedin: Users,
  whatsapp: PhoneCall,
  telegram: Send,
};
